base_models:
  - name: logistic_regression
    params:
      C: 1.0
      penalty: l2
  - name: random_forest
    params:
      n_estimators: 100
      max_depth: 5
  - name: xgboost
    params:
      n_estimators: 100
      learning_rate: 0.1

meta_model:
  name: logistic_regression
  params:
    C: 1.0
    penalty: l2

cv_folds: 5
save_path: models/